name: Check
on:
  workflow_call:
    inputs:
      toolchain:
        description: Rust toolchain
        required: true
        type: string

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # TODO: Keep this updated
        target:
          - x86_64-unknown-none
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - name: Install ${{ matrix.target }} target
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ inputs.toolchain }}
          target: ${{ matrix.target }}
          components: clippy, rustfmt
          rustflags: -W warnings
          cache: true
          cache-workspaces: ./charlotte_core
      - name: Check code style with "cargo fmt"
        run: cargo fmt --check --manifest-path charlotte_core/Cargo.toml
      - name: Check code with "cargo check"
        run: cargo check --target ${{ matrix.target }} --manifest-path charlotte_core/Cargo.toml
      - name: Check code with "Clippy"
        run: cargo clippy --target ${{ matrix.target }} --manifest-path charlotte_core/Cargo.toml
      - name: List of lint disables
        run: grep -rn '#\[allow\(.*\)\]' ./charlotte_core/src/
